apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../base
patches:
  - target:
      kind: Service
      name: store-front
    patch: |
      - op: replace
        path: /spec/ports/0/port
        value: 8070
namespace: pets-qa
